export const DEFAULT_SITE_SETTINGS = {
  siteName: "DropEarn",
  siteDescription: "Upload. Share. Earn. The transparent, legitimate monetized file-sharing platform.",
  logoUrl: "/logo.svg",
  maintenanceMode: false,
  uploaderRevenuePercent: 50,
  platformRevenuePercent: 50,
  minWithdrawal: 10.0,
  maxFileSizeMb: 500,
  allowedMimeTypes: [
    "application/pdf",
    "application/zip",
    "application/x-zip-compressed",
    "application/x-rar-compressed",
    "application/x-7z-compressed",
    "application/x-tar",
    "application/gzip",
    "image/png",
    "image/jpeg",
    "image/gif",
    "image/webp",
    "image/svg+xml",
    "video/mp4",
    "video/webm",
    "audio/mpeg",
    "audio/wav",
    "audio/ogg",
    "text/plain",
    "text/markdown",
    "text/csv",
    "application/json",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  ],
  adProviderEnabled: false,
  adProviderKey: "DIRECT",
  adSensePublisherId: "",
  registrationEnabled: true,
};

export const FILE_CATEGORIES = [
  "General",
  "Documents",
  "Archives",
  "Images",
  "Audio",
  "Video",
  "Software",
  "Other",
] as const;

export const QUALIFICATION_RULES = {
  COOLDOWN_PER_IP_HOURS: 6,
  MAX_DAILY_QUALIFIED_PER_IP: 3,
  MIN_TIME_ON_PAGE_SECONDS: 5,
  BASE_QUALIFIED_REVENUE_PER_DOWNLOAD: 0.02, // $0.02 base per qualified download (or from provider)
};
