"use client";

import React, { useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/Button";
import { AdPlacementSlot } from "@/components/monetization/AdPlacementSlot";
import { HelpCircle, ChevronDown, ChevronUp, ArrowRight } from "lucide-react";

export default function FAQPage() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const FAQS = [
    {
      q: "How do I earn money on DropEarn?",
      a: "Upload any legal file (documents, software, media, archives) up to 100 MB each. When visitors download your file through your share link and complete the download process, you earn revenue according to the visitor's geographic tier.",
    },
    {
      q: "What is a 'qualified download'?",
      a: "A download is qualified when a genuine visitor accesses your download page, waits through the verification dwell time, and initiates the download. Automated bots, self-downloads, proxy abuse, and rapid repeated clicks from the same IP are filtered out by our anti-fraud system.",
    },
    {
      q: "What is the minimum payout amount and what payout methods are supported?",
      a: "The minimum withdrawal threshold is $10.00. We support PayPal, USDT (TRC20/ERC20), Bitcoin, and Direct Bank Transfer.",
    },
    {
      q: "How does the referral program work?",
      a: "When you refer other creators with your unique referral link, you receive 10% lifetime commission on all download revenue generated by your referrals, paid directly from the platform share without reducing their earnings.",
    },
    {
      q: "Are there storage limits?",
      a: "Free creator accounts have a 1 GB storage quota and a 100 MB single file upload limit. You can delete inactive files at any time to free up storage space.",
    },
    {
      q: "What content is prohibited on DropEarn?",
      a: "We strictly prohibit malware, spyware, phishing tools, child exploitation, terrorism, copyright-infringing content without authorization, and any illegal material. Violations result in immediate file removal and account termination.",
    },
  ];

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-8">
      {/* Top Banner */}
      <AdPlacementSlot location="BANNER" format="horizontal" />

      <div className="text-center space-y-3">
        <h1 className="text-3xl sm:text-4xl font-black text-white tracking-tight">
          Frequently Asked <span className="gradient-text">Questions</span>
        </h1>
        <p className="text-xs sm:text-sm text-slate-400">
          Everything you need to know about uploading, monetization, and withdrawals on DropEarn.
        </p>
      </div>

      {/* Accordion FAQ Card */}
      <div className="rounded-3xl glass-card p-6 sm:p-8 border border-slate-800 space-y-4">
        {FAQS.map((faq, idx) => {
          const isOpen = openIndex === idx;
          return (
            <div
              key={idx}
              className="rounded-2xl bg-slate-900/60 border border-slate-800 overflow-hidden transition-colors"
            >
              <button
                type="button"
                onClick={() => setOpenIndex(isOpen ? null : idx)}
                className="w-full p-5 text-left flex items-center justify-between gap-4 text-sm font-semibold text-white hover:text-blue-400 transition-colors"
              >
                <span>{faq.q}</span>
                {isOpen ? (
                  <ChevronUp className="w-4 h-4 text-blue-400 shrink-0" />
                ) : (
                  <ChevronDown className="w-4 h-4 text-slate-500 shrink-0" />
                )}
              </button>
              {isOpen && (
                <div className="px-5 pb-5 text-xs text-slate-300 leading-relaxed border-t border-slate-800/80 pt-3 animate-fade-in">
                  {faq.a}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* 2. Bottom Ad Placement */}
      <div>
        <AdPlacementSlot location="FAQ_BOTTOM" format="horizontal" />
      </div>
    </div>
  );
}
