"use client";

import React, { useEffect, useState } from "react";
import { formatCurrency, formatDate } from "@/lib/utils";
import { StatCard } from "@/components/ui/StatCard";
import { Button } from "@/components/ui/Button";
import { EmptyState } from "@/components/ui/EmptyState";
import { Users, DollarSign, Percent, Copy, Check, Share2, Loader2 } from "lucide-react";

export default function ReferralsPage() {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    fetch("/api/v1/referrals")
      .then((res) => (res.ok ? res.json() : null))
      .then((resData) => {
        if (resData) setData(resData);
      })
      .catch((err) => console.error("Referrals error:", err))
      .finally(() => setLoading(false));
  }, []);

  const handleCopyLink = () => {
    if (!data?.referralLink) return;
    const fullUrl = `${window.location.origin}${data.referralLink}`;
    navigator.clipboard.writeText(fullUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (loading) {
    return (
      <div className="flex h-64 items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-blue-500" />
      </div>
    );
  }

  const referralList = data?.referrals || [];

  return (
    <div className="space-y-8">
      {/* Header */}
      <div>
        <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
          Referral Program
        </h1>
        <p className="text-xs sm:text-sm text-slate-400 mt-1">
          Invite other creators to DropEarn and earn a 10% commission on platform revenue generated by their files.
        </p>
      </div>

      {/* Metrics Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
        <StatCard
          title="Total Referred Users"
          value={data?.totalReferrals || 0}
          subtitle="Signed up with your link"
          icon={<Users className="w-5 h-5 text-blue-400" />}
        />

        <StatCard
          title="Commission Earned"
          value={formatCurrency(data?.totalEarned || "0.00")}
          subtitle="Lifetime referral earnings"
          icon={<DollarSign className="w-5 h-5 text-emerald-400" />}
          highlight={true}
        />

        <StatCard
          title="Commission Rate"
          value={data?.commissionRate || "10%"}
          subtitle="Of platform revenue share"
          icon={<Percent className="w-5 h-5 text-purple-400" />}
        />
      </div>

      {/* Referral Link Box */}
      <div className="rounded-2xl glass-card p-6 sm:p-8 border border-slate-800">
        <h3 className="text-base font-bold text-white mb-2 flex items-center gap-2">
          <Share2 className="w-4 h-4 text-blue-400" />
          <span>Your Unique Referral Link</span>
        </h3>
        <p className="text-xs text-slate-400 mb-4">
          Share this link with fellow creators. When they register, you will automatically receive referral bonuses on their downloads.
        </p>

        <div className="flex flex-col sm:flex-row items-center gap-3">
          <input
            type="text"
            readOnly
            value={
              typeof window !== "undefined"
                ? `${window.location.origin}${data?.referralLink || ""}`
                : data?.referralLink || ""
            }
            className="w-full sm:flex-1 px-4 py-2.5 rounded-xl bg-slate-900 border border-slate-700 text-blue-400 font-mono text-sm outline-none"
          />
          <Button onClick={handleCopyLink} size="md" className="w-full sm:w-auto shrink-0">
            {copied ? (
              <>
                <Check className="w-4 h-4 text-emerald-400 mr-1.5" />
                <span>Copied!</span>
              </>
            ) : (
              <>
                <Copy className="w-4 h-4 mr-1.5" />
                <span>Copy Referral Link</span>
              </>
            )}
          </Button>
        </div>
      </div>

      {/* Referred Users Table */}
      <div className="rounded-2xl glass-card p-6 border border-slate-800">
        <h3 className="text-base font-bold text-white mb-4">
          Referred Creators
        </h3>

        {referralList.length === 0 ? (
          <EmptyState
            icon={<Users className="w-6 h-6" />}
            title="No referrals yet"
            description="Share your referral link with other creators to start earning passive commissions."
            actionLabel="Copy Link"
            onAction={handleCopyLink}
          />
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="border-b border-slate-800 text-slate-400 font-semibold uppercase tracking-wider">
                <tr>
                  <th className="py-3 px-3">Creator</th>
                  <th className="py-3 px-3">Date Joined</th>
                  <th className="py-3 px-3 text-right">Commission Earned</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800/60 text-slate-300">
                {referralList.map((r: any) => (
                  <tr key={r.id} className="hover:bg-slate-800/40">
                    <td className="py-3 px-3 font-medium text-white">
                      {r.user.displayName || r.user.email}
                    </td>
                    <td className="py-3 px-3 text-slate-400">
                      {formatDate(r.createdAt)}
                    </td>
                    <td className="py-3 px-3 font-semibold text-emerald-400 text-right">
                      {formatCurrency(r.earned)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
